const fs = require('fs');
const assert = require('assert');
const media = fs.readFileSync('modules/utils/media.js', 'utf8');
const admin = fs.readFileSync('admin_contact_ui_patch.js', 'utf8');
const page = fs.readFileSync('index.html', 'utf8');
const slip = fs.readFileSync('admin_floating_cart_patch.js', 'utf8');
assert.match(media, /IMAGE_UPLOAD_MAX_BYTES = 720000/, 'ภาพ inline ต้องจำกัด raw bytes ที่ 720 KB เพื่อให้ Base64 ไม่เกิน 1 MB');
assert.match(media, /file\.size > 40 \* 1000000/, 'ต้องปฏิเสธไฟล์ต้นฉบับที่ใหญ่เกินความปลอดภัย');
assert.match(media, /image\/webp/, 'ต้องใช้ WebP สำหรับ PNG/WebP เมื่อบีบอัด');
assert.match(admin, /bindPromotionImage[\s\S]*?compressImageForUpload\(file\)/, 'ภาพโฆษณาต้องผ่านตัวบีบอัดกลาง');
assert.match(admin, /data-store-detail-image-input[\s\S]*?compressImageForUpload\(file\)/, 'รูปและพื้นหลังร้านต้องผ่านตัวบีบอัดกลาง');
assert.match(page, /bindFileAsDataUrl[\s\S]*?compressImageForUpload\(file\)/, 'โลโก้ Hero QR และรูปเมนูต้องผ่านตัวบีบอัดกลาง');
assert.match(slip, /compressImageForUpload\(file, \{ maxBytes: 720000, maxDimension: 1600 \}\)/, 'สลิปต้องไม่เกิน 720 KB ก่อนเก็บใน Storage');
assert.doesNotMatch(slip, /reader\.readAsDataURL\(file\)/, 'ห้ามมี fallback อ่านสลิปเต็มไฟล์โดยไม่บีบอัด');
console.log('admin image 1 MB hard-cap contract: PASS');
const bridge = fs.readFileSync('modules/legacy-bridge.js', 'utf8');
assert.match(bridge, /media\.js\?v=img-hardcap-v1/, 'ต้อง cache-bust โมดูล media เพื่อไม่ให้ runtime ใช้เพดานเก่าจาก cache');
assert.match(page, /modules\/boot\.js\?v=performance-storage-v2/, 'ต้อง cache-bust boot module เพื่อให้โหลด bridge เวอร์ชันใหม่');
const boot = fs.readFileSync('modules/boot.js', 'utf8');
assert.match(boot, /legacy-bridge\.js\?v=performance-storage-v2/, 'ต้อง cache-bust legacy bridge เพื่อให้ media module ใหม่ทำงานที่ runtime');
assert.match(page, /modules\/boot\.js\?v=performance-storage-v2/, 'ต้อง cache-bust boot อีกครั้งหลังแก้ import chain');
