const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const content = fs.readFileSync(path.join(root, 'customer/customer-content-runtime.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'customer/customer-app.js'), 'utf8');
const retail = fs.readFileSync(path.join(root, 'customer/customer-retail-patch.js'), 'utf8');
const parcel = fs.readFileSync(path.join(root, 'customer/customer-parcel.js'), 'utf8');
const migration = fs.readFileSync(path.join(root, 'supabase/migrations/20260820_customer_parcel_a_to_b.sql'), 'utf8');
assert.match(content, /href: 'stores\.html\?service=food'/, 'Food must open the food-scoped catalogue');
assert.match(content, /href: 'retail\.html'/, 'Supermarket must open the unified retail surface');
assert.match(content, /id: 'parcel'/, 'Home service registry must include A→B delivery');
assert.match(app, /const foodOnly = q\.get\('service'\) === 'food'/, 'Stores must understand the food service scope');
assert.match(app, /String\(store\.category_id\) !== 'store-supermarket'/, 'Food scope must exclude the supermarket category');
assert.match(app, /page === 'parcel'/, 'Customer router must mount parcel page');
assert.match(retail, /ซูเปอร์มาร์เก็ตและสินค้าทั่วไป/, 'Retail surface must identify the merged service');
assert.doesNotMatch(retail, /data-retail-home-link/, 'Retail patch must not inject a duplicate Home card');
assert.match(parcel, /create_customer_parcel_delivery/, 'Parcel UI must call the server-authorized RPC');
assert.match(parcel, /customer_addresses\?select=/, 'Parcel UI must use saved addresses with real locations for dropoff');
assert.match(migration, /SECURITY DEFINER/, 'Parcel create RPC must be server-authorized');
assert.match(migration, /private\.has_role\('customer'\)/, 'Parcel create RPC must validate customer role');
assert.match(migration, /v_distance := 6371/, 'Parcel fee distance must be computed server-side');
assert.match(migration, /'parcel'/, 'Parcel create RPC must use the parcel business rules');
assert.match(migration, /'ร้านค้ารับออร์เดอร์'/, 'Parcel must enter the existing Rider claim queue');
console.log('customer service routing and parcel contract: PASS');
