const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'customer', 'customer-app.js'), 'utf8');
const runtime = fs.readFileSync(path.join(root, 'shared', 'ap-service-mpa.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'customer', 'customer-auth.css'), 'utf8');
const profile = fs.readFileSync(path.join(root, 'customer', 'profile.html'), 'utf8');
assert.match(runtime, /async function signInWithOAuth\(provider, redirectTo/);
assert.match(runtime, /auth\.signInWithOAuth\(/);
assert.match(runtime, /location\.assign\(result\.data\.url\)/);
assert.match(app, /data-social-provider="google"/);
assert.match(app, /data-social-provider="facebook"/);
assert.match(app, /data-social-provider="line"/);
assert.match(app, /socialButtons\.forEach/);
assert.match(app, /M\.ui\.setNotice\(`ขออภัย การล็อกอินด้วย \$\{label\} ยังไม่พร้อมให้บริการ`, 'warning'\)/);
assert.doesNotMatch(app, /socialButtons\.forEach\(button => button\.addEventListener\('click', async/);
assert.match(css, /customer-social-button--google/);
assert.match(css, /customer-social-button--facebook/);
assert.match(css, /customer-social-button--line/);
assert.match(profile, /customer-auth-v4-social-providers/);
assert.match(profile, /customer-auth-v9-social-login-disabled/);
console.log('customer social login unavailable contract: PASS');
