const fs = require('fs');
const assert = require('assert');

const runtime = fs.readFileSync('shared/ap-service-mpa.js', 'utf8');
const app = fs.readFileSync('customer/customer-app.js', 'utf8');
const registerPage = fs.readFileSync('customer/register.html', 'utf8');
const registerRuntime = fs.readFileSync('customer/customer-register.js', 'utf8');
const recoverRuntime = fs.readFileSync('customer/customer-recover.js', 'utf8');
const updatePasswordRuntime = fs.readFileSync('customer/customer-update-password.js', 'utf8');
const recoverPage = fs.readFileSync('customer/recover.html', 'utf8');
const updatePasswordPage = fs.readFileSync('customer/update-password.html', 'utf8');
const admin = fs.readFileSync('../Apservicebeta/admin/admin-app.js', 'utf8');

assert.match(runtime, /async function signUp/, 'Shared runtime may retain signUp internally for Admin-provisioned workflows');
assert.match(app, /registerForm|auth\.signUp|mode=register/, 'Customer app must expose the public Customer registration flow');
assert.match(app, /register\.html\?next=/, 'Customer registration must open on its own route instead of an inline popup');
assert.match(registerPage, /customer-register\.js/, 'Registration page must load its dedicated runtime');
assert.match(registerRuntime, /registerFullName|registerPhone|registerAddress|registerConsent/, 'Registration must collect essential account, contact, delivery, and consent information');
assert.match(registerRuntime, /user_profiles\?on_conflict=user_id/, 'Signed-in registration must persist contact and delivery details');
assert.match(registerRuntime, /user_consents/, 'Registration must create an auditable required-consent record when a session is available');
assert.match(registerRuntime, /offerRecovery|recover\.html/, 'Registration must offer account recovery when an existing account or incomplete auth result is detected');
assert.match(registerRuntime, /identities\.length === 0/, 'Registration must recognize Supabase anti-enumeration responses for an existing email and direct to recovery');
assert.match(runtime, /sendPasswordRecovery|acceptRecoveryFromHash|updatePassword/, 'Shared auth runtime must support password recovery and password update');
assert.match(recoverRuntime, /sendPasswordRecovery/, 'Recovery page must send a password-recovery email through the shared runtime');
assert.match(updatePasswordRuntime, /acceptRecoveryFromHash|updatePassword/, 'Recovery completion page must accept a recovery session before updating a password');
assert.match(recoverPage, /defer src="customer-recover\.js/, 'Recovery runtime must wait for its body before rendering the form');
assert.match(updatePasswordPage, /defer src="customer-update-password\.js/, 'Password update runtime must wait for its body before rendering the form');
assert.match(app, /APLoginUI\?\.enhance/, 'Customer Login must use shared Login UI motion helper');
assert.match(app, /สมัครสมาชิก Customer|สมัครสมาชิกด้วยอีเมลและรหัสผ่าน/, 'Customer Login must explain and expose self-registration');
assert.match(app, /rolesFor\(session\.user\.id\)/, 'Customer Login must check role after sign-in');
assert.match(app, /roles\.includes\('customer'\)/, 'Customer registration must verify the customer role after signup');
assert.match(app, /registered=pending/, 'Customer registration must handle email-confirmation flows');
assert.match(app, /customerAuthActions/, 'Protected Customer pages must expose login and signup actions');
assert.match(admin, /create_managed_account/, 'Admin must keep managed account creation');
assert.match(admin, /role: 'store_owner'/, 'Merchant provisioning must remain Admin-owned');
assert.match(admin, /rider-applications|riders\.html/, 'Rider account workflow must remain Admin-owned');
assert.match(app, /select=display_name,phone,email,address/, 'Customer profile must still read saved address');
assert.match(app, /id="address"/, 'Customer profile must still edit delivery address');

console.log('customer self-signup/auth contract: PASS');
