const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const content = fs.readFileSync(path.join(root, 'customer/customer-content-runtime.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'customer/customer-app.js'), 'utf8');
const retail = fs.readFileSync(path.join(root, 'customer/customer-retail-patch.js'), 'utf8');
const parcel = fs.readFileSync(path.join(root, 'customer/customer-parcel.js'), 'utf8');
const migration = fs.readFileSync(path.join(root, 'supabase/migrations/20260820_customer_parcel_a_to_b.sql'), 'utf8');
const receiptMigration = fs.readFileSync(path.join(root, 'supabase/migrations/20260820_customer_parcel_receipt_estimate.sql'), 'utf8');
const locationPicker = fs.readFileSync(path.join(root, 'customer/customer-location-picker.js'), 'utf8');
const parcelEntrypoint = fs.readFileSync(path.join(root, 'customer/parcel.html'), 'utf8');
const shared = fs.readFileSync(path.join(root, 'shared/ap-service-mpa.js'), 'utf8');
assert.match(content, /href: 'stores\.html\?service=food'/, 'Food must open the food-scoped catalogue');
assert.match(content, /href: 'retail\.html'/, 'Supermarket must open the unified retail surface');
assert.match(content, /id: 'parcel'/, 'Home service registry must include A→B delivery');
assert.match(app, /const foodOnly = q\.get\('service'\) === 'food'/, 'Stores must understand the food service scope');
assert.match(app, /String\(store\.category_id\) !== 'store-supermarket'/, 'Food scope must exclude the supermarket category');
assert.match(app, /page === 'parcel'/, 'Customer router must mount parcel page');
assert.match(retail, /ซูเปอร์มาร์เก็ตและสินค้าทั่วไป/, 'Retail surface must identify the merged service');
assert.doesNotMatch(retail, /data-retail-home-link/, 'Retail patch must not inject a duplicate Home card');
assert.match(parcel, /create_customer_parcel_delivery/, 'Parcel UI must call the server-authorized RPC');
assert.match(parcel, /estimate_customer_parcel_delivery/, 'Parcel UI must request an authoritative estimate before creating an order');
assert.match(parcel, /ELECTRONIC DELIVERY SUMMARY/, 'Parcel UI must present an electronic summary before confirmation');
assert.match(parcel, /ยืนยันและเรียกไรเดอร์/, 'Parcel receipt must require a second confirmation');
assert.match(parcel, /customer_parcel_hero/, 'Parcel UI must consume Admin-configured hero media');
assert.match(parcel, /customer_parcel_sponsored/, 'Parcel UI must consume Admin-configured sponsored media');
assert.match(parcel, /customer_addresses\?select=/, 'Parcel UI must use saved addresses with real locations for dropoff');
assert.match(locationPicker, /mountParcel/, 'Location module must expose a reusable Parcel picker');
assert.match(locationPicker, /ใช้ตำแหน่งปัจจุบัน/, 'Parcel picker must support GPS');
assert.match(locationPicker, /เลือกบนแผนที่/, 'Parcel picker must support a map pin');
assert.match(locationPicker, /กรอกพิกัดเอง/, 'Parcel picker must support manual coordinates');
assert.match(parcelEntrypoint, /customer-location-picker\.js/, 'Parcel entrypoint must load the reusable picker');
assert.match(receiptMigration, /estimate_customer_parcel_delivery/, 'Receipt estimate must be server-authorized');
assert.match(receiptMigration, /private\.has_role\('customer'\)/, 'Receipt estimate must validate customer role');
assert.match(receiptMigration, /v_distance := 6371/, 'Receipt estimate must calculate server-side distance');
assert.match(receiptMigration, /'service_type', 'parcel'/, 'Receipt estimate must identify the shared parcel order type');
assert.match(shared, /installImageSourceChoices/, 'Customer shared runtime must enhance image inputs');
assert.match(shared, /ถ่ายรูปด้วยกล้อง/, 'Customer upload enhancer must expose camera source');
assert.match(migration, /SECURITY DEFINER/, 'Parcel create RPC must be server-authorized');
assert.match(migration, /private\.has_role\('customer'\)/, 'Parcel create RPC must validate customer role');
assert.match(migration, /v_distance := 6371/, 'Parcel fee distance must be computed server-side');
assert.match(migration, /'parcel'/, 'Parcel create RPC must use the parcel business rules');
assert.match(migration, /'ร้านค้ารับออร์เดอร์'/, 'Parcel must enter the existing Rider claim queue');
console.log('customer service routing and parcel contract: PASS');
