const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const runtime = fs.readFileSync(path.join(root, 'shared', 'ap-service-mpa.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'customer', 'customer-app.js'), 'utf8');
const register = fs.readFileSync(path.join(root, 'customer', 'customer-register.js'), 'utf8');
const callback = fs.readFileSync(path.join(root, 'customer', 'customer-auth-callback.js'), 'utf8');
const callbackPage = fs.readFileSync(path.join(root, 'customer', 'auth-callback.html'), 'utf8');
const emailTemplate = fs.readFileSync(path.join(root, 'supabase', 'templates', 'customer_magic_link.html'), 'utf8');

assert.match(runtime, /async function sendMagicLink\(email, redirectTo/, 'Shared runtime must expose a magic-link request');
assert.match(runtime, /auth\.signInWithOtp\(/, 'Magic-link flow must use Supabase Auth Client');
assert.match(runtime, /shouldCreateUser: createUser !== false/, 'Magic-link flow must preserve the Customer onboarding policy');
assert.match(runtime, /emailRedirectTo: redirectTo/, 'Magic-link flow must pass the callback destination through Supabase Auth Client');
assert.match(runtime, /async function processCallback\(\)/, 'Shared runtime must expose one canonical callback processor');
assert.match(app, /auth-callback\.html/, 'Customer Login must use a dedicated callback route');
assert.match(app, /M\.auth\.sendMagicLink\(email, callback\.href/, 'Customer Login must request the link with the callback URL');
assert.doesNotMatch(app, /id="password"/, 'Customer Login must not render a password field');
assert.match(register, /sendMagicLink/, 'Customer registration must use the same passwordless flow');
assert.doesNotMatch(register, /registerPassword/, 'Customer registration must not ask for a password');
assert.match(callback, /processCallback\(\)/, 'Callback must use the canonical one-time auth processor');
assert.match(callback, /onboardingState\(user, profile\)/, 'Incomplete profiles must be routed to onboarding');
assert.match(callback, /user_profiles\?on_conflict=user_id/, 'Onboarding must persist required customer profile data');
assert.match(callback, /user_consents/, 'Onboarding must persist consent evidence');
assert.match(callback, /reloadIntoApp/, 'Successful callback must return to the requested application route');
assert.match(callback, /customer-success-motion/, 'Successful callback must show the branded processing motion');
assert.match(callback, /650/, 'Successful callback must keep the processing motion visible before opening the application');
assert.match(callback, /reloadIntoApp/, 'Successful callback must reload or replace into the application automatically');
assert.match(callback, /window\.location\.replace\(url\.href\)/, 'Successful callback must replace the callback route with the application route');
assert.match(callbackPage, /customer-auth-callback\.css\?v=auth-callback-v2-motion/, 'Callback page must load the branded callback stylesheet revision');
assert.match(callbackPage, /customer-auth-callback\.js\?v=auth-callback-v4-verify-link-validity/, 'Callback page must load the current callback runtime revision');
assert.match(runtime, /exchangeCodeForSession\(code\)/, 'Shared runtime must support a PKCE code callback');
assert.match(runtime, /auth\.exchangeCodeForSession\(String\(code\)\.trim\(\)\)/, 'PKCE exchange must use Supabase Auth Client');
assert.match(runtime, /verifyMagicLinkTokenHash\(tokenHash\)/, 'Shared runtime must support the official token_hash callback variant');
assert.match(runtime, /auth\.verifyOtp\(\{ token_hash: String\(tokenHash\)\.trim\(\), type: 'email' \}\)/, 'Token-hash verification must use Supabase Auth Client');
assert.match(emailTemplate, /\{\{ \.ConfirmationURL \}\}/, 'Magic-link email template must use Supabase ConfirmationURL');
console.log('customer magic-link callback contract: PASS');
