const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const page = fs.readFileSync(path.join(root, 'customer/order.html'), 'utf8');
const state = fs.readFileSync(path.join(root, 'customer/customer-order-financial-state.js'), 'utf8');
const roleAccess = fs.readFileSync(path.join(root, 'supabase/functions/role-access/index.ts'), 'utf8');
const refundMigration = fs.readFileSync(path.join(root, 'supabase/migrations/20260820_admin_order_refund_workflow.sql'), 'utf8');
assert.match(page, /customer-order-financial-state\.js/, 'Customer Order Detail must load the financial state surface');
assert.match(state, /order_payments\?select=/, 'Customer must read the real order_payments state');
assert.match(state, /order_refunds\?select=/, 'Customer must read the real order_refunds state');
assert.match(state, /order_financial_events\?select=/, 'Customer must read the financial timeline');
assert.match(state, /refundLabel/, 'Customer must translate refund state for the customer');
assert.match(state, /startBackgroundSync/, 'Customer financial state must refresh without a full navigation');
assert.match(roleAccess, /body\.action === 'process_order_refund'/, 'Role Access must expose the allow-listed refund action');
assert.match(roleAccess, /admin_process_order_refund/, 'Role Access must call the audited refund RPC');
assert.match(refundMigration, /CREATE FUNCTION public\.admin_process_order_refund/, 'Backend must define the audited refund RPC');
assert.match(refundMigration, /idempotency_key/, 'Refund workflow must preserve idempotency');
assert.match(roleAccess, /body\.action === 'support_conversation'/, 'Role Access must expose the Support Inbox action');
assert.match(roleAccess, /support_messages/, 'Support action must write messages through the central server');
assert.match(roleAccess, /deep_link: 'support\.html'/, 'Support action must send Customer deep-link notifications');
console.log('customer_financial_state_contract_test: PASS');
