(() => {
  'use strict';
  const M = window.APServiceMPA;
  const C = window.APServiceCore;
  const $ = selector => document.querySelector(selector);
  const h = M.ui.escapeHtml;
  const page = document.body.dataset.page;
  const links = [['dashboard','ภาพรวม'],['orders','ออร์เดอร์'],['stores','ร้านค้า'],['customers','ลูกค้า'],['riders','ไรเดอร์'],['finance','การเงิน'],['notifications','แจ้งเตือน'],['ai-workspace','AI Workspace'],['settings','ตั้งค่ากลาง']];
  const nav = active => `<header class="mpa-topbar"><a class="mpa-brand" href="dashboard.html">AP Service · Admin Control Plane</a><nav class="mpa-nav">${links.map(([key,label]) => `<a class="${key===active?'active':''}" href="${key}.html">${label}</a>`).join('')}<a href="../admin.html">Fallback</a></nav></header>`;
  const app = (active, content) => { document.body.innerHTML = `${nav(active)}<main class="mpa-shell" data-page-content>${content}</main>`; };
  const countRows = async path => { const rows = await M.request(path, { private: true }); return Array.isArray(rows) ? rows.length : 0; };
  async function gate(active, content) {
    app(active, content);
    return M.auth.requireRole('admin', { loginUrl: 'index.html', container: $('[data-page-content]') });
  }
  async function login() {
    document.body.innerHTML = `<main class="mpa-shell" style="min-height:100vh;display:grid;place-items:center" data-page-content>${M.ui.loading('กำลังเปิดศูนย์ควบคุมหลังบ้าน…')}</main>`;
    const signedInUser = await M.auth.currentUser();
    if (signedInUser) {
      const roles = await M.auth.rolesFor(signedInUser.id).catch(() => []);
      if (roles.includes('admin')) { location.replace('dashboard.html'); return; }
    }
    document.body.innerHTML = `<main class="mpa-shell" style="min-height:100vh;display:grid;place-items:center"><section class="mpa-card" style="width:min(430px,100%)"><div style="text-align:center"><div style="width:48px;height:48px;border-radius:16px;margin:auto;display:grid;place-items:center;background:#0b8c7c;color:#fff;font-weight:950">AP</div><h1>เข้าสู่ศูนย์ควบคุมหลังบ้าน</h1><p class="mpa-muted">เข้าสู่ระบบด้วยบัญชีที่ได้รับสิทธิ์ Admin ใน Supabase</p></div><form id="loginForm"><div class="mpa-field"><label>อีเมล</label><input id="email" type="email" autocomplete="email" autofocus required></div><div class="mpa-field"><label>รหัสผ่าน</label><input id="password" type="password" autocomplete="current-password" required></div><button class="mpa-button" style="width:100%">เข้าสู่หลังบ้าน</button></form><p class="mpa-muted" style="text-align:center;margin:16px 0 0"><a href="../admin.html">เปิดระบบเดิม (fallback)</a></p></section></main>`;
    $('#loginForm').onsubmit = async event => { event.preventDefault(); try { const session = await M.auth.signIn($('#email').value.trim(), $('#password').value); const roles = await M.auth.rolesFor(session.user.id); if (!roles.includes('admin')) { M.auth.signOut('index.html'); throw new Error('บัญชีนี้ไม่มีสิทธิ์ Admin'); } location.assign('dashboard.html'); } catch (error) { M.ui.setNotice(error.message, 'error'); } };
  }
  async function dashboard() {
    const access = await gate('dashboard', `<div class="mpa-page-head"><div><h1>ภาพรวมงานหลังบ้าน</h1><p>เปลี่ยนหน้าแล้วแสดง shell ทันที จากนั้นโหลดสรุปข้อมูลแบบ background</p></div><button class="mpa-button mpa-button-secondary" id="signOut">ออกจากระบบ</button></div><div class="mpa-grid stats" id="stats">${M.ui.loading('กำลังสรุปงานค้าง…')}</div><section class="mpa-card" style="margin-top:18px"><h2 style="margin-top:0">งานที่ต้องตรวจสอบ</h2><div id="pending">${M.ui.loading('กำลังอ่านรายการล่าสุด…')}</div></section>`); if (!access) return;
    $('#signOut').onclick = () => M.auth.signOut('index.html');
    try { const [orders, stores, riders, withdrawals] = await Promise.all([countRows('delivery_orders?select=id&status=neq.สำเร็จแล้ว&limit=500'), countRows('stores?select=id&active=eq.true&limit=500'), countRows('riders?select=id&status=eq.พร้อมรับงาน&limit=500'), countRows('withdrawal_requests?select=id&status=eq.pending&limit=500').catch(() => 0)]); $('#stats').innerHTML = `<div class="mpa-card mpa-stat"><small>ออร์เดอร์ที่ยังดำเนินการ</small><strong>${orders}</strong></div><div class="mpa-card mpa-stat"><small>ร้านค้าเปิดบริการ</small><strong>${stores}</strong></div><div class="mpa-card mpa-stat"><small>ไรเดอร์พร้อมรับงาน</small><strong>${riders}</strong></div><div class="mpa-card mpa-stat"><small>คำขอถอนเงินรอตรวจ</small><strong>${withdrawals}</strong></div>`; $('#pending').innerHTML = `<p class="mpa-muted">ใช้เมนู <a href="orders.html">ออร์เดอร์</a>, <a href="finance.html">การเงิน</a> และ <a href="settings.html">ตั้งค่ากลาง</a> เพื่อดำเนินงานแต่ละประเภท ข้อมูลนี้รีเฟรชหลัง shell แสดงแล้ว จึงไม่ block navigation</p>`; } catch (err) { $('#stats').innerHTML = M.ui.error('โหลดสรุปไม่สำเร็จ', err.message); }
  }
  async function orders() {
    const access = await gate('orders', `<div class="mpa-page-head"><div><h1>จัดการออร์เดอร์</h1><p>เปลี่ยนสถานะตาม Shared Core และสิทธิ์ Admin ใน RLS</p></div></div><section id="orders" class="mpa-card">${M.ui.loading('กำลังโหลดออร์เดอร์…')}</section>`); if (!access) return;
    try { const rows = await M.request('delivery_orders?select=id,store_name,customer_name,status,total,payable,ordered_at&order=ordered_at.desc&limit=150', { private: true }); const statuses = Object.values(C.contracts.orderStatus); $('#orders').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>เวลา</th><th>ร้าน/ลูกค้า</th><th>สถานะ</th><th>ยอด</th><th>เปลี่ยนสถานะ</th></tr></thead><tbody>${rows.map(row => `<tr><td>${new Date(row.ordered_at).toLocaleString('th-TH')}</td><td><b>${h(row.store_name || '-')}</b><br><span class="mpa-muted">${h(row.customer_name || '-')}</span></td><td><span class="mpa-badge">${h(row.status)}</span></td><td>${M.ui.baht(row.payable ?? row.total)}</td><td><select data-status="${h(row.id)}"><option value="">เลือกสถานะ…</option>${statuses.filter(status => status !== row.status).map(status => `<option value="${h(status)}">${h(status)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีออร์เดอร์'); document.querySelectorAll('[data-status]').forEach(select => select.onchange = async () => { if (!select.value) return; const row = rows.find(item => item.id === select.dataset.status); const check = C.order.canTransition({ from: row.status, to: select.value, actor: 'admin' }); if (!check.ok) return M.ui.setNotice(check.reason, 'error'); try { await M.request(`delivery_orders?id=eq.${encodeURIComponent(row.id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ status: select.value, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกสถานะแล้ว'); setTimeout(() => location.reload(), 350); } catch (err) { M.ui.setNotice(err.message, 'error'); } }); } catch (err) { $('#orders').innerHTML = M.ui.error('โหลดออร์เดอร์ไม่สำเร็จ', err.message); }
  }
  async function stores() {
    const access = await gate('stores', `<div class="mpa-page-head"><div><h1>ร้านค้าและ Merchant</h1><p>ตรวจรายการร้านค้าและสถานะเปิดบริการ</p></div></div><section id="stores" class="mpa-card">${M.ui.loading('กำลังโหลดร้านค้า…')}</section>`); if (!access) return;
    try { const rows = await M.request('stores?select=id,name,owner_email,phone,rating,eta,active,image_url,background_url&order=name.asc&limit=250', { private: true }); $('#stores').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ร้านค้า</th><th>ติดต่อ</th><th>คะแนน</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${rows.map(row => `<tr><td><b>${h(row.name)}</b><br><span class="mpa-muted">${h(row.eta || '')}</span></td><td>${h(row.owner_email || row.phone || '-')}</td><td>${Number(row.rating || 0).toFixed(1)}</td><td><span class="mpa-badge">${row.active ? 'เปิดบริการ' : 'ปิดบริการ'}</span></td><td><button class="mpa-button mpa-button-secondary" data-toggle="${h(row.id)}">${row.active ? 'ปิดร้าน' : 'เปิดร้าน'}</button></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีร้านค้า'); document.querySelectorAll('[data-toggle]').forEach(button => button.onclick = async () => { const row = rows.find(item => item.id === button.dataset.toggle); try { await M.request(`stores?id=eq.${encodeURIComponent(row.id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ active: !row.active }) }); M.ui.setNotice('บันทึกสถานะร้านแล้ว'); setTimeout(() => location.reload(), 350); } catch (err) { M.ui.setNotice(err.message, 'error'); } }); } catch (err) { $('#stores').innerHTML = M.ui.error('โหลดร้านค้าไม่สำเร็จ', err.message); }
  }
  async function customers() {
    const access = await gate('customers', `<div class="mpa-page-head"><div><h1>ลูกค้าและโปรไฟล์</h1><p>อ่านข้อมูลตาม RLS ของ Admin</p></div></div><section id="customers" class="mpa-card">${M.ui.loading('กำลังโหลดลูกค้า…')}</section>`); if (!access) return;
    try { const rows = await M.request('user_profiles?select=user_id,display_name,email,phone,created_at&order=created_at.desc&limit=250', { private: true }); $('#customers').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>โทรศัพท์</th><th>เริ่มใช้งาน</th></tr></thead><tbody>${rows.map(row => `<tr><td>${h(row.display_name || '-')}</td><td>${h(row.email || '-')}</td><td>${h(row.phone || '-')}</td><td>${row.created_at ? new Date(row.created_at).toLocaleDateString('th-TH') : '-'}</td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีข้อมูลลูกค้า'); } catch (err) { $('#customers').innerHTML = M.ui.error('โหลดข้อมูลลูกค้าไม่สำเร็จ', err.message); }
  }
  async function riders() {
    const access = await gate('riders', `<div class="mpa-page-head"><div><h1>ไรเดอร์และการปฏิบัติงาน</h1><p>ติดตามสถานะและข้อมูลผู้จัดส่ง</p></div></div><section id="riders" class="mpa-card">${M.ui.loading('กำลังโหลดไรเดอร์…')}</section>`); if (!access) return;
    try { const rows = await M.request('riders?select=id,name,phone,vehicle,status,updated_at&order=name.asc&limit=250', { private: true }); $('#riders').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ชื่อ</th><th>โทรศัพท์</th><th>ยานพาหนะ</th><th>สถานะ</th></tr></thead><tbody>${rows.map(row => `<tr><td>${h(row.name)}</td><td>${h(row.phone || '-')}</td><td>${h(row.vehicle || '-')}</td><td><span class="mpa-badge">${h(row.status || '-')}</span></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีข้อมูลไรเดอร์'); } catch (err) { $('#riders').innerHTML = M.ui.error('โหลดข้อมูลไรเดอร์ไม่สำเร็จ', err.message); }
  }
  async function finance() {
    const access = await gate('finance', `<div class="mpa-page-head"><div><h1>การเงินและคำขอถอน</h1><p>ข้อมูลการเงินโหลดเฉพาะหน้าที่มีสิทธิ์ Admin</p></div></div><section id="finance" class="mpa-card">${M.ui.loading('กำลังโหลดคำขอถอนเงิน…')}</section>`); if (!access) return;
    try { const rows = await M.request('withdrawal_requests?select=*&order=created_at.desc&limit=150', { private: true }); $('#finance').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>สร้างเมื่อ</th><th>ผู้รับเงิน</th><th>จำนวน</th><th>สถานะ</th></tr></thead><tbody>${rows.map(row => `<tr><td>${row.created_at ? new Date(row.created_at).toLocaleString('th-TH') : '-'}</td><td>${h(row.requester_name || row.rider_name || row.user_name || '-')}</td><td>${M.ui.baht(row.amount || row.requested_amount || 0)}</td><td><span class="mpa-badge">${h(row.status || '-')}</span></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ไม่มีคำขอถอนเงินที่ต้องจัดการ'); } catch (err) { $('#finance').innerHTML = M.ui.error('โหลดข้อมูลการเงินไม่สำเร็จ', err.message); }
  }
  async function notifications() {
    const access = await gate('notifications', `<div class="mpa-page-head"><div><h1>การแจ้งเตือน</h1><p>ติดตามข้อความและงานที่รอการดำเนินการ</p></div></div><section id="notifications" class="mpa-card">${M.ui.loading('กำลังโหลดการแจ้งเตือน…')}</section>`); if (!access) return;
    try { const rows = await M.request('mobile_notifications?select=id,title,body,created_at,read_at&order=created_at.desc&limit=150', { private: true }); $('#notifications').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>เวลา</th><th>หัวข้อ</th><th>ข้อความ</th><th>อ่านแล้ว</th></tr></thead><tbody>${rows.map(row => `<tr><td>${row.created_at ? new Date(row.created_at).toLocaleString('th-TH') : '-'}</td><td>${h(row.title || '-')}</td><td>${h(row.body || '-')}</td><td>${row.read_at ? 'แล้ว' : 'ยังไม่อ่าน'}</td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีการแจ้งเตือน'); } catch (err) { $('#notifications').innerHTML = M.ui.error('โหลดการแจ้งเตือนไม่สำเร็จ', err.message); }
  }
  async function aiWorkspace() {
    const access = await gate('ai-workspace', `<div class="mpa-page-head"><div><h1>AI Collaboration Workspace</h1><p>ศูนย์งานร่วมกับ AI สำหรับผู้ดูแลระบบ</p></div></div><section class="mpa-card"><h2 style="margin-top:0">เชื่อมต่อพื้นที่ทำงาน</h2><p class="mpa-muted">หน้านี้สงวนไว้สำหรับข้อมูล AI Workspace เท่านั้น และจะไม่โหลดข้อมูลออร์เดอร์หรือการเงินเพื่อรักษาขอบเขตของแต่ละ MPA route</p><a class="mpa-button" href="../admin.html">เปิด AI Workspace แบบ Compatibility Fallback</a></section>`); if (!access) return;
  }
  async function settings() {
    const access = await gate('settings', `<div class="mpa-page-head"><div><h1>ตั้งค่าธุรกิจกลาง</h1><p>Admin Control Plane: ค่าที่อนุญาตจะบันทึกผ่าน RLS ใน platform_configs</p></div></div><section id="settings" class="mpa-card">${M.ui.loading('กำลังโหลดการตั้งค่ากลาง…')}</section>`); if (!access) return;
    try { const rows = await M.request('platform_configs?select=key,value,updated_at&order=key.asc&limit=100', { private: true }); $('#settings').innerHTML = `<p class="mpa-muted">เปลี่ยนเฉพาะ key ที่ได้รับอนุมัติเท่านั้น กฎด้านการเงินและความปลอดภัยยังต้องมี Server/RLS เป็นผู้บังคับใช้</p><div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>Key</th><th>Value (JSON)</th><th>อัปเดต</th><th></th></tr></thead><tbody>${(rows || []).map(row => `<tr><td><b>${h(row.key)}</b></td><td><textarea data-value="${h(row.key)}" rows="2">${h(JSON.stringify(row.value ?? {}))}</textarea></td><td>${row.updated_at ? new Date(row.updated_at).toLocaleString('th-TH') : '-'}</td><td><button class="mpa-button" data-save="${h(row.key)}">บันทึก</button></td></tr>`).join('') || `<tr><td colspan="4">ยังไม่มี configuration ที่ได้รับอนุมัติให้แก้ไข</td></tr>`}</tbody></table></div>`; document.querySelectorAll('[data-save]').forEach(button => button.onclick = async () => { const key = button.dataset.save, field = document.querySelector(`[data-value="${CSS.escape(key)}"]`); let value; try { value = JSON.parse(field.value); } catch { return M.ui.setNotice('ค่า configuration ต้องอยู่ในรูปแบบ JSON ที่ถูกต้อง', 'error'); } try { await M.request('platform_configs?on_conflict=key', { method: 'POST', private: true, headers: { Prefer: 'resolution=merge-duplicates,return=minimal' }, body: JSON.stringify({ key, value, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกการตั้งค่ากลางแล้ว'); } catch (err) { M.ui.setNotice(err.message, 'error'); } }); } catch (err) { $('#settings').innerHTML = M.ui.error('โหลดการตั้งค่ากลางไม่สำเร็จ', err.message); }
  }
  ({ login, dashboard, orders, stores, customers, riders, finance, notifications, 'ai-workspace': aiWorkspace, settings }[page] || login)();
})();
